#include "mu/tiny/test.hpp"

TEST_GROUP_C_WRAPPER(MutinyC)
{
  TEST_GROUP_C_SETUP_WRAPPER(MutinyC)
  TEST_GROUP_C_TEARDOWN_WRAPPER(MutinyC)
};

TEST_C_WRAPPER(MutinyC, checkThatTheTestHasRun)
SKIPPED_TEST_C_WRAPPER(MutinyC, ignoreMacroForCFile)
TEST_C_WRAPPER(MutinyC, bool)
TEST_C_WRAPPER(MutinyC, boolText)
TEST_C_WRAPPER(MutinyC, int)
TEST_C_WRAPPER(MutinyC, intText)
TEST_C_WRAPPER(MutinyC, unsignedInt)
TEST_C_WRAPPER(MutinyC, unsignedIntText)
TEST_C_WRAPPER(MutinyC, long)
TEST_C_WRAPPER(MutinyC, longText)
TEST_C_WRAPPER(MutinyC, ulong)
TEST_C_WRAPPER(MutinyC, ulongText)
TEST_C_WRAPPER(MutinyC, longLong)
TEST_C_WRAPPER(MutinyC, longLongText)
TEST_C_WRAPPER(MutinyC, uLongLong)
TEST_C_WRAPPER(MutinyC, uLongLongText)
TEST_C_WRAPPER(MutinyC, real)
TEST_C_WRAPPER(MutinyC, realText)
TEST_C_WRAPPER(MutinyC, char)
TEST_C_WRAPPER(MutinyC, charText)
TEST_C_WRAPPER(MutinyC, uByte)
TEST_C_WRAPPER(MutinyC, uByteText)
TEST_C_WRAPPER(MutinyC, sByte)
TEST_C_WRAPPER(MutinyC, sbyteText)
TEST_C_WRAPPER(MutinyC, string)
TEST_C_WRAPPER(MutinyC, stringText)
TEST_C_WRAPPER(MutinyC, pointer)
TEST_C_WRAPPER(MutinyC, pointerText)
TEST_C_WRAPPER(MutinyC, memcmp)
TEST_C_WRAPPER(MutinyC, memcmpText)
TEST_C_WRAPPER(MutinyC, check)
TEST_C_WRAPPER(MutinyC, checkText)
XFAIL_TEST_C_WRAPPER(MutinyC, boolFail)
XFAIL_TEST_C_WRAPPER(MutinyC, boolTextFail)
XFAIL_TEST_C_WRAPPER(MutinyC, intFail)
XFAIL_TEST_C_WRAPPER(MutinyC, intTextFail)
XFAIL_TEST_C_WRAPPER(MutinyC, unsignedIntFail)
XFAIL_TEST_C_WRAPPER(MutinyC, unsignedIntTextFail)
XFAIL_TEST_C_WRAPPER(MutinyC, longFail)
XFAIL_TEST_C_WRAPPER(MutinyC, longTextFail)
XFAIL_TEST_C_WRAPPER(MutinyC, ulongFail)
XFAIL_TEST_C_WRAPPER(MutinyC, ulongTextFail)
XFAIL_TEST_C_WRAPPER(MutinyC, longLongFail)
XFAIL_TEST_C_WRAPPER(MutinyC, longLongTextFail)
XFAIL_TEST_C_WRAPPER(MutinyC, uLongLongFail)
XFAIL_TEST_C_WRAPPER(MutinyC, uLongLongTextFail)
XFAIL_TEST_C_WRAPPER(MutinyC, realFail)
XFAIL_TEST_C_WRAPPER(MutinyC, realTextFail)
XFAIL_TEST_C_WRAPPER(MutinyC, charFail)
XFAIL_TEST_C_WRAPPER(MutinyC, charTextFail)
XFAIL_TEST_C_WRAPPER(MutinyC, uByteFail)
XFAIL_TEST_C_WRAPPER(MutinyC, uByteTextFail)
XFAIL_TEST_C_WRAPPER(MutinyC, sByteFail)
XFAIL_TEST_C_WRAPPER(MutinyC, sbyteTextFail)
XFAIL_TEST_C_WRAPPER(MutinyC, stringFail)
XFAIL_TEST_C_WRAPPER(MutinyC, stringTextFail)
XFAIL_TEST_C_WRAPPER(MutinyC, pointerFail)
XFAIL_TEST_C_WRAPPER(MutinyC, pointerTextFail)
XFAIL_TEST_C_WRAPPER(MutinyC, memcmpFail)
XFAIL_TEST_C_WRAPPER(MutinyC, memcmpTextFail)
XFAIL_TEST_C_WRAPPER(MutinyC, failText)
XFAIL_TEST_C_WRAPPER(MutinyC, fail)
XFAIL_TEST_C_WRAPPER(MutinyC, checkFail)
XFAIL_TEST_C_WRAPPER(MutinyC, checkTextFail)
