#include "mutiny/test.hpp"

TEST_GROUP_C_WRAPPER(MutinyC)
{
  TEST_GROUP_C_SETUP_WRAPPER(MutinyC)
  TEST_GROUP_C_TEARDOWN_WRAPPER(MutinyC)
};

TEST_C_WRAPPER(MutinyC, checkThatTheTestHasRun)
IGNORE_TEST_C_WRAPPER(MutinyC, ignoreMacroForCFile)
TEST_C_WRAPPER(MutinyC, bool)
TEST_C_WRAPPER(MutinyC, boolText)
TEST_C_WRAPPER(MutinyC, int)
TEST_C_WRAPPER(MutinyC, intText)
TEST_C_WRAPPER(MutinyC, unsignedInt)
TEST_C_WRAPPER(MutinyC, unsignedIntText)
TEST_C_WRAPPER(MutinyC, long)
TEST_C_WRAPPER(MutinyC, longText)
TEST_C_WRAPPER(MutinyC, ulong)
TEST_C_WRAPPER(MutinyC, ulongText)
TEST_C_WRAPPER(MutinyC, longLong)
TEST_C_WRAPPER(MutinyC, longLongText)
TEST_C_WRAPPER(MutinyC, uLongLong)
TEST_C_WRAPPER(MutinyC, uLongLongText)
TEST_C_WRAPPER(MutinyC, real)
TEST_C_WRAPPER(MutinyC, realText)
TEST_C_WRAPPER(MutinyC, char)
TEST_C_WRAPPER(MutinyC, charText)
TEST_C_WRAPPER(MutinyC, uByte)
TEST_C_WRAPPER(MutinyC, uByteText)
TEST_C_WRAPPER(MutinyC, sByte)
TEST_C_WRAPPER(MutinyC, sbyteText)
TEST_C_WRAPPER(MutinyC, string)
TEST_C_WRAPPER(MutinyC, stringText)
TEST_C_WRAPPER(MutinyC, pointer)
TEST_C_WRAPPER(MutinyC, pointerText)
TEST_C_WRAPPER(MutinyC, memcmp)
TEST_C_WRAPPER(MutinyC, memcmpText)
TEST_C_WRAPPER(MutinyC, check)
TEST_C_WRAPPER(MutinyC, checkText)
EXPECT_FAIL_TEST_C_WRAPPER(MutinyC, boolFail)
EXPECT_FAIL_TEST_C_WRAPPER(MutinyC, boolTextFail)
EXPECT_FAIL_TEST_C_WRAPPER(MutinyC, intFail)
EXPECT_FAIL_TEST_C_WRAPPER(MutinyC, intTextFail)
EXPECT_FAIL_TEST_C_WRAPPER(MutinyC, unsignedIntFail)
EXPECT_FAIL_TEST_C_WRAPPER(MutinyC, unsignedIntTextFail)
EXPECT_FAIL_TEST_C_WRAPPER(MutinyC, longFail)
EXPECT_FAIL_TEST_C_WRAPPER(MutinyC, longTextFail)
EXPECT_FAIL_TEST_C_WRAPPER(MutinyC, ulongFail)
EXPECT_FAIL_TEST_C_WRAPPER(MutinyC, ulongTextFail)
EXPECT_FAIL_TEST_C_WRAPPER(MutinyC, longLongFail)
EXPECT_FAIL_TEST_C_WRAPPER(MutinyC, longLongTextFail)
EXPECT_FAIL_TEST_C_WRAPPER(MutinyC, uLongLongFail)
EXPECT_FAIL_TEST_C_WRAPPER(MutinyC, uLongLongTextFail)
EXPECT_FAIL_TEST_C_WRAPPER(MutinyC, realFail)
EXPECT_FAIL_TEST_C_WRAPPER(MutinyC, realTextFail)
EXPECT_FAIL_TEST_C_WRAPPER(MutinyC, charFail)
EXPECT_FAIL_TEST_C_WRAPPER(MutinyC, charTextFail)
EXPECT_FAIL_TEST_C_WRAPPER(MutinyC, uByteFail)
EXPECT_FAIL_TEST_C_WRAPPER(MutinyC, uByteTextFail)
EXPECT_FAIL_TEST_C_WRAPPER(MutinyC, sByteFail)
EXPECT_FAIL_TEST_C_WRAPPER(MutinyC, sbyteTextFail)
EXPECT_FAIL_TEST_C_WRAPPER(MutinyC, stringFail)
EXPECT_FAIL_TEST_C_WRAPPER(MutinyC, stringTextFail)
EXPECT_FAIL_TEST_C_WRAPPER(MutinyC, pointerFail)
EXPECT_FAIL_TEST_C_WRAPPER(MutinyC, pointerTextFail)
EXPECT_FAIL_TEST_C_WRAPPER(MutinyC, memcmpFail)
EXPECT_FAIL_TEST_C_WRAPPER(MutinyC, memcmpTextFail)
EXPECT_FAIL_TEST_C_WRAPPER(MutinyC, failText)
EXPECT_FAIL_TEST_C_WRAPPER(MutinyC, fail)
EXPECT_FAIL_TEST_C_WRAPPER(MutinyC, checkFail)
EXPECT_FAIL_TEST_C_WRAPPER(MutinyC, checkTextFail)
