FROM ubuntu

RUN apt-get update && \
    apt-get install -y -q --no-install-recommends cmake git gcc g++ make

WORKDIR /cpputest_build

COPY ../ /cpputest

CMD ["bash", "-c", "cmake --preset GNU /cpputest && cmake --build . && ctest --output-on-failure"]
